### ISSUE TITLE
Merge upstream/gh-pages branch to master

### ISSUE THREAD

**Issue by tkruse** [cpplint/cpplint#59]
Fetching upstream changes should be made easy, for that we regularly need to merge upstream gh-pages branch into our master branch. We should do this as a no-op merge once this list of PRs has been merged:
* [x] #52
* [x] #51 
* [x] #53 (after rebase and tests pass)
* [x] #53 (after rebase and tests pass)
* [x] #55 (after rebase and tests pass)
* [x] #56 (after rebase and tests pass)
* [x] #57 (after rebase and tests pass)
* [x] #58 (after rebase and tests pass)

**Comment by tkruse** [comment]
all merged
